### PR TITLE
ORCID 2.1 generated source based on ORCID-Source XSDs on 2018-04-23

### PR DESCRIPTION
**Pull request by tdonohue**
This PR is an initial attempt at generating ORCID v2.1 Java source code, based on the ORCID-Source XSDs at: https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/resources

This Java Source code was generated via the instructions in our [README](https://github.com/DSpace/orcid-jaxb-api/blob/master/README.md).  

It currently ONLY includes the following XSDs:
* All XSDs in [common_2.1](https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/resources/common_2.1)
* All XSDs in [record_2.1](https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/resources/record_2.1)

The custom JAXB binding (loosely based off DSpace-CRIS's) used to generate this source code is stored in this repo at: https://github.com/DSpace/orcid-jaxb-api/blob/master/src/main/resources/binding/orcid-2.1.xjb  Comments or updates on that binding also welcome -- submit a PR or add a comment here.

While the generated Java source code need not be versioned / stored in GitHub, I'd recommend doing so, simply as a reference for developers. Otherwise, debugging issues in generated code may be more complex. Additionally, storing generated source code in GitHub allows us to more easily version it / tag it, etc.

Feedback welcome. 

*PLEASE DO NOT MERGE* until we verify this helps simplify https://github.com/DSpace/DSpace/pull/2028

**HOW TO TEST**
* FOR EASIER TESTING, I've deployed this as a SNAPSHOT to Sonatype: https://oss.sonatype.org/content/repositories/snapshots/org/dspace/orcid-jaxb-api/2.1.0-SNAPSHOT/
* If you do not want to use the SNAPSHOT version in Sonatype, you can build locally by doing this:
    * Checkout this PR's branch, and build the `orcid-jaxb-api-2.1.0-SNAPSHOT.jar` (via `mvn -U clean package`)
    * Install thar JAR manually in your local Maven:
       ```
       mvn install:install-file
        -Dfile=orcid-jaxb-api-2.1.0-SNAPSHOT.jar
        -DgroupId=org.dspace
        -DartifactId=orcid-jaxb-api
        -Dversion=2.1.0-SNAPSHOT
        -Dpackaging=jar
        -DgeneratePom=true
       ```
* Checkout https://github.com/DSpace/DSpace/pull/2028
* Add this dependency to the root POM, e.g.
  ```
  <dependency>
      <groupId>org.dspace</groupId>
      <artifactId>orcid-jaxb-api</artifactId>
      <version>2.1.0-SNAPSHOT</version>
  </dependency>
  ```
* Remove all `org.orcid.*` source files added by https://github.com/DSpace/DSpace/pull/2028
* As needed, update https://github.com/DSpace/DSpace/pull/2028 code to use any new package/class names in this `orcid-jaxb-api` project.

### CODE REVIEW

**Comment by lap82** [comment]
+1 @tdonohue good job! I read documentation and it's the same approach that we using in DSpace-CRIS. The only difference it is the package name used for custom JAXB binding. We choosed to have "org.dspace.authority.orcid.jaxb.*" but in your binding the package is mapped on "org.orcid.jaxb.*". This binding file is used to naming packages and to inferred the right element for certain type not managed by the default classes generation (e.g. EducationsType, and so on...). By now maybe it is the best choice your mapping, because usually the code generated should be as-is the XSDs declared. Thank you.

**Comment by tdonohue** [comment]
I've updated/rebased this PR with a major enhancement:
* In the first commit, I've now updated our custom JAXB bindings (XJB) to create Java classes/packages that mirror those in ORCID-model: https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/java/
* In the second commit, I've (re)generated all the Java source code, using this updated XJB.  The class names/packages now align more with ORCID (it's not a 100% match, but it's close). 
* I also rebased this on latest `master` (which now includes Travis CI build verification).

I'm hoping these changes make it even easier for https://github.com/DSpace/DSpace/pull/2028 to adopt this code.

**Comment by tdonohue** [comment]
Today I've deployed a copy of the results of this PR as a `2.1.0-SNAPSHOT` version in Sonatype:
https://oss.sonatype.org/content/repositories/snapshots/org/dspace/orcid-jaxb-api/2.1.0-SNAPSHOT/

This means that you can reference it for testing, by simply adding this dependency to the DSpace POM:
```
  <dependency>
      <groupId>org.dspace</groupId>
      <artifactId>orcid-jaxb-api</artifactId>
      <version>2.1.0-SNAPSHOT</version>
  </dependency>
```
AND  adding this to the DSpace Parent POM (to ensure it looks at Sonatype for SNAPSHOT releases):
```
    <!-- Enable access to artifacts in Sonatype's snapshot repo for Snapshots ONLY -->
    <repositories>
        <repository>
          <id>maven-snapshots</id>
          <url>http://oss.sonatype.org/content/repositories/snapshots</url>
          <layout>default</layout>
            <releases>
              <enabled>false</enabled>
            </releases>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
    </repositories>
```

**Review by kshepherd — APPROVED** [review]
+1 I've used this in conjunction with DSpace PR#2039 and it works as advertised!

**Pull request merged**
